//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAD_KAA_Entities.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALEX-PC\\SQLEXPRESS2012;Initial Catalog=\"SIAD_KAA Soluciones\";User ID=" +
            "SIAD-KAA; Password=SIAD-KAA123")]
        public string SIAD_KAA_SolucionesConnectionString {
            get {
                return ((string)(this["SIAD_KAA_SolucionesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALEX-PC\\SQLEXPRESS2012;Initial Catalog=\"SIAD_KAA Soluciones\";User ID=" +
            "SA")]
        public string SIAD_KAA_SolucionesConnectionString1 {
            get {
                return ((string)(this["SIAD_KAA_SolucionesConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALEX-PC\\SQLEXPRESS2012;Initial Catalog=\"SIAD_KAA Soluciones\";Persist " +
            "Security Info=True;User ID=SA")]
        public string SIAD_KAA_SolucionesConnectionString2 {
            get {
                return ((string)(this["SIAD_KAA_SolucionesConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALEX-PC\\SQLEXPRESS2012;Initial Catalog=SIAD_KAA;Persist Security Info" +
            "=True;User ID=sa;Password=123")]
        public string SIAD_KAAConnectionString {
            get {
                return ((string)(this["SIAD_KAAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALEX-PC\\SQLEXPRESS2012;Initial Catalog=SIAD_KAA;Persist Security Info" +
            "=True;User ID=SIAD-KAA")]
        public string SIAD_KAAConnectionString1 {
            get {
                return ((string)(this["SIAD_KAAConnectionString1"]));
            }
        }
    }
}
