DROP PROCEDURE SP_TIPOS_MENU_POR_USUARIO
GO

CREATE PROCEDURE SP_TIPOS_MENU_POR_USUARIO
	@PK_ROL SMALLINT
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT
		DISTINCT(P.PAG_TIPO)
	FROM
		SIAD_PAGINAS_POR_ROL AS PPR
		,SIAD_ROLES AS R
		,SIAD_PAGINAS AS P
	WHERE
		 PPR.PK_ROL = @PK_ROL
		 AND PPR.PK_PAGINA = P.PK_PAGINA
		 AND P.PAG_ESTADO = 'A' 
		 AND R.ROL_ESTADO = 'A'
	ORDER BY P.PAG_TIPO ASC
END
GO

----------------------------------------------------------------------
DROP PROCEDURE SP_VERIFICAR_USUARIO
GO

CREATE PROCEDURE SP_VERIFICAR_USUARIO
	@USU_USUARIO VARCHAR(20),
	@USU_CONTRASEÑA VARCHAR(20)
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT
		PK_USUARIO
		,PK_ROL
		,PK_RESTAURANTE
		,USU_PRIMER_NOMBRE
		,USU_USUARIO
	FROM
		SIAD_USUARIOS
	WHERE
		 USU_USUARIO = @USU_USUARIO 
		 AND USU_CONTRASEÑA = @USU_CONTRASEÑA
END
GO

------------------------------------------------------------------------


DROP PROCEDURE SP_LISTAR_PAGINAS_POR_TIPO
GO

CREATE PROCEDURE SP_LISTAR_PAGINAS_POR_TIPO
@PAG_TIPO VARCHAR(50),
@PK_ROL SMALLINT
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT
		PPR.PPR_INGRESO
		,PPR.PPR_MODIFICACION
		,PPR.PPR_ELIMINACION
		,PPR.PPR_CREACION
		,P.PK_PAGINA
		,P.PAG_RUTA
		,P.PAG_TIPO
		,P.PAG_ICONO
		,P.PAG_NOMBRE
	FROM
		SIAD_PAGINAS_POR_ROL AS PPR,
		SIAD_PAGINAS AS P
	WHERE
		 PPR.PK_ROL = @PK_ROL
		 AND PPR.PK_PAGINA = P.PK_PAGINA
		 AND P.PAG_TIPO = @PAG_TIPO
		 AND P.PAG_ESTADO = 'A'
	ORDER BY P.PAG_NOMBRE ASC
END
GO


-----------------------------------------------------------

DROP PROCEDURE SP_LISTAR_MENU_POR_RESTAURANTE
GO

CREATE PROCEDURE SP_LISTAR_MENU_POR_RESTAURANTE
@PK_RESTAURANTE SMALLINT
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_MENUS AS M,
		SIAD_PORCIONES AS P,
		SIAD_TIPO_MENU
	WHERE
		 M.PK_RESTAURANTE = @PK_RESTAURANTE
		 AND M.MEN_ESTADO = 'A'
END
GO

---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_PORCIONES
GO

CREATE PROCEDURE SP_LISTAR_PORCIONES
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_PORCIONES 
	WHERE
		  POR_ESTADO = 'A'
END
GO

---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_TIPOS_MENU
GO

CREATE PROCEDURE SP_LISTAR_TIPOS_MENU
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_TIPO_MENU 
	WHERE
		  TIM_ESTADO = 'A'
END
GO

---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_RESTAURANTES
GO

CREATE PROCEDURE SP_LISTAR_RESTAURANTES
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_RESTAURANTE 
	WHERE
		  RES_ESTADO = 'A'
END
GO

---------------------------------------------------------

DROP PROCEDURE SP_REGISTRAR_MENU
GO

CREATE PROCEDURE SP_REGISTRAR_MENU
@PK_PORCION AS SMALLINT,
@PK_RESTAURANTE AS SMALLINT,
@PK_TIPO_MENU AS SMALLINT,
@MEN_CODIGO AS VARCHAR(30),
@MEN_NOMBRE AS VARCHAR(50),
@MEN_IMAGEN AS IMAGE,
@MEN_PRECIO AS DECIMAL(8,2),
@MEN_PRECIO_IVI AS DECIMAL(8,2),
@MEN_DESCUENTO AS DECIMAL(4,2),
@MEN_ESTADO AS VARCHAR(1),
@MEN_CREADO_POR AS VARCHAR(20)
AS
BEGIN 
	SET NOCOUNT ON;
    INSERT INTO SIAD_MENUS(
		PK_PORCION,
		PK_RESTAURANTE,
		PK_TIPO_MENU,
		MEN_CODIGO,
		MEN_NOMBRE,
		MEN_IMAGEN,
		MEN_PRECIO,
		MEN_PRECIO_IVI,
		MEN_DESCUENTO,
		MEN_ESTADO,
		MEN_CREADO_POR,
		MEN_FECHA_CREACION)
	VALUES(
		@PK_PORCION ,
		@PK_RESTAURANTE,
		@PK_TIPO_MENU ,
		@MEN_CODIGO ,
		@MEN_NOMBRE ,
		@MEN_IMAGEN ,
		@MEN_PRECIO ,
		@MEN_PRECIO_IVI ,
		@MEN_DESCUENTO ,
		@MEN_ESTADO ,
		@MEN_CREADO_POR,
		GETDATE())
END
GO


---------------------------------------------------------

DROP PROCEDURE SP_MODIFICAR_MENU
GO

CREATE PROCEDURE SP_MODIFICAR_MENU
@PK_MENU AS SMALLINT,
@PK_PORCION AS SMALLINT,
@PK_RESTAURANTE AS SMALLINT,
@MEN_NOMBRE AS VARCHAR(50),
@MEN_IMAGEN AS IMAGE,
@MEN_PRECIO AS DECIMAL(8,2),
@MEN_PRECIO_IVI AS DECIMAL(8,2),
@MEN_DESCUENTO AS DECIMAL(4,2),
@MEN_ESTADO AS VARCHAR(1),
@MEN_MODIFICADO_POR AS VARCHAR(20)
AS
BEGIN 
	SET NOCOUNT ON;
    UPDATE SIAD_MENUS SET
		PK_PORCION = @PK_PORCION,
		PK_RESTAURANTE = @PK_RESTAURANTE,
		MEN_NOMBRE = @MEN_NOMBRE,
		MEN_IMAGEN = @MEN_IMAGEN,
		MEN_PRECIO = @MEN_PRECIO,
		MEN_PRECIO_IVI = @MEN_PRECIO_IVI,
		MEN_DESCUENTO = @MEN_DESCUENTO,
		MEN_ESTADO = @MEN_ESTADO,
		MEN_MODIFICADO_POR = @MEN_MODIFICADO_POR,
		MEN_FECHA_MODIFICACION = GETDATE()
	WHERE
		PK_MENU = @PK_MENU
END
GO


---------------------------------------------------------

DROP PROCEDURE SP_ELIMINAR_MENU
GO

CREATE PROCEDURE SP_ELIMINAR_MENU
@PK_MENU AS SMALLINT
AS
BEGIN 
	SET NOCOUNT ON;
    DELETE SIAD_MENUS
	WHERE
		PK_MENU = @PK_MENU
END
GO

---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_MENU
GO

CREATE PROCEDURE SP_LISTAR_MENU
@PK_TIPO_MENU AS SMALLINT,
@MEN_NOMBRE AS VARCHAR(50)
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_MENUS 
	WHERE
		(PK_TIPO_MENU = @PK_TIPO_MENU OR @PK_TIPO_MENU = 0)
		AND (MEN_NOMBRE LIKE '%' + @MEN_NOMBRE + '%')  
		AND MEN_ESTADO = 'A'
END
GO


---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_MENU_POR_TIPO_MENU
GO

CREATE PROCEDURE SP_LISTAR_MENU_POR_TIPO_MENU
@PK_TIPO_MENU AS SMALLINT
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_MENUS 
	WHERE
		PK_TIPO_MENU = @PK_TIPO_MENU 
		AND MEN_ESTADO = 'A'
END
GO




---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_MENU_POR_PK
GO

CREATE PROCEDURE SP_LISTAR_MENU_POR_PK
@PK_MENU AS SMALLINT
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_MENUS 
	WHERE
		PK_MENU = @PK_MENU 
		AND MEN_ESTADO = 'A'
END
GO


---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_PARAMETRO_GENERAL_POR_NOMBRE
GO

CREATE PROCEDURE SP_LISTAR_PARAMETRO_GENERAL_POR_NOMBRE
@PGE_NOMBRE AS VARCHAR(50)
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_PARAMETROS_GENERALES 
	WHERE
		PGE_NOMBRE = @PGE_NOMBRE 
		AND PGE_ESTADO = 'A'
END
GO


---------------------------------------------------------

DROP PROCEDURE SP_MODIFCAR_CODIGO_MENU_RESTAURANTE
GO

CREATE PROCEDURE SP_MODIFCAR_CODIGO_MENU_RESTAURANTE
@PK_RESTAURANTE AS SMALLINT,
@RES_CODIGO_MENU AS VARCHAR(20),
@RES_MODIFICADO_POR VARCHAR(20)
AS
BEGIN 
	SET NOCOUNT ON;
    UPDATE SIAD_RESTAURANTE SET
		RES_CODIGO_MENU = @RES_CODIGO_MENU,
		RES_MODIFICADO_POR = @RES_MODIFICADO_POR,
		RES_FECHA_MODIFICACION = GETDATE()
	WHERE
		PK_RESTAURANTE = @PK_RESTAURANTE
END
GO



---------------------------------------------------------

DROP PROCEDURE SP_LISTAR_MESAS
GO

CREATE PROCEDURE SP_LISTAR_MESAS
AS
BEGIN 
	SET NOCOUNT ON;
    SELECT *
	FROM
		SIAD_MESAS 
	WHERE
		MES_ESTADO = 'A'
END
GO

---------------------------------------------------------

DROP PROCEDURE SP_REGISTRAR_MESA
GO

CREATE PROCEDURE SP_REGISTRAR_MESA
@PK_RESTAURANTE AS SMALLINT,
@MES_NUMERO AS SMALLINT,
@MES_DESCRIPCION AS VARCHAR(50),
@MES_ESTADO_ACTUAL AS VARCHAR(50),
@MES_ESTADO AS VARCHAR(1),
@MES_CREADO_POR AS VARCHAR(20)
AS
BEGIN 
	SET NOCOUNT ON;
    INSERT INTO SIAD_MESAS(
		PK_RESTAURANTE,
		MES_NUMERO,
		MES_DESCRIPCION,
		MES_ESTADO_ACTUAL,
		MES_ESTADO,
		MES_CREADO_POR,
		MES_FECHA_CREACION)
	VALUES(
		@PK_RESTAURANTE,
		@MES_NUMERO ,
		@MES_DESCRIPCION ,
		@MES_ESTADO_ACTUAL ,
		@MES_ESTADO ,
		@MES_CREADO_POR,
		GETDATE())
END
GO


---------------------------------------------------------

DROP PROCEDURE SP_MODIFICAR_MESA
GO

CREATE PROCEDURE SP_MODIFICAR_MESA
@PK_MESA AS SMALLINT,
@PK_RESTAURANTE AS SMALLINT,
@MES_NUMERO AS SMALLINT,
@MES_DESCRIPCION AS VARCHAR(50),
@MES_ESTADO_ACTUAL AS VARCHAR(50),
@MES_ESTADO AS VARCHAR(1),
@MES_MODIFICADO_POR AS VARCHAR(20)
AS
BEGIN 
	SET NOCOUNT ON;
    UPDATE SIAD_MESAS SET
		PK_RESTAURANTE = @PK_RESTAURANTE,
		MES_NUMERO = @MES_NUMERO,
		MES_DESCRIPCION = @MES_DESCRIPCION,
		MES_ESTADO_ACTUAL = @MES_ESTADO_ACTUAL,
		MES_ESTADO = @MES_ESTADO,
		MES_MODIFICADO_POR = @MES_MODIFICADO_POR,
		MES_FECHA_MODIFICACION = GETDATE()
	WHERE
		PK_MESA = @PK_MESA
END
GO


---------------------------------------------------------

DROP PROCEDURE SP_ELIMINAR_MESA
GO

CREATE PROCEDURE SP_ELIMINAR_MESA
@PK_MESA AS SMALLINT
AS
BEGIN 
	SET NOCOUNT ON;
    DELETE SIAD_MESAS
	WHERE
		PK_MESA = @PK_MESA
END
GO
