CREATE TABLE SIAD_RESTAURANTE(
	PK_RESTAURANTE SMALLINT IDENTITY(1,1) NOT NULL,
	RES_NOMBRE VARCHAR(50) DEFAULT('') NOT NULL,
	RES_LOGO IMAGE NULL,
	RES_TELEFONO_UNO VARCHAR(20) DEFAULT('') NOT NULL,
	RES_TELEFONO_DOS VARCHAR(20) DEFAULT('') NOT NULL,
	RES_CEDULA_JURIDICA VARCHAR(30) DEFAULT('') NOT NULL,
	RES_CORREO_ELECTRONICO VARCHAR(100) DEFAULT('') NOT NULL,
	RES_DIRECCION VARCHAR(200) DEFAULT('') NOT NULL,
	RES_CODIGO_MENU VARCHAR(20) DEFAULT('00000') NOT NULL,
	RES_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	RES_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	RES_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	RES_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	RES_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_RESTAURANTE PRIMARY KEY NONCLUSTERED (PK_RESTAURANTE)) 
 

 ----------------------------------------------------------------------------------------------------
 
 CREATE TABLE SIAD_ROLES(
	PK_ROL SMALLINT IDENTITY(1,1) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	ROL_NOMBRE VARCHAR(30) DEFAULT('') NOT NULL,
	ROL_DESCRIPCION VARCHAR(50) DEFAULT('') NOT NULL,
	ROL_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	ROL_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	ROL_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	ROL_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	ROL_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_ROLES PRIMARY KEY NONCLUSTERED (PK_ROL, PK_RESTAURANTE))
 
 ALTER TABLE SIAD_ROLES ADD CONSTRAINT FK_SIAD_RES_ROL FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE) 
 
----------------------------------------------------------------------------------------------------

CREATE TABLE SIAD_USUARIOS(
	PK_USUARIO SMALLINT IDENTITY(1,1) NOT NULL,
	PK_ROL SMALLINT DEFAULT(0) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	USU_PRIMER_NOMBRE VARCHAR(30) DEFAULT('') NOT NULL,
	USU_SEGUNDO_NOMBRE VARCHAR(30) DEFAULT('') NOT NULL,
	USU_PRIMER_APELLIDO VARCHAR(30) DEFAULT('') NOT NULL,
	USU_SEGUNDO_APELLIDO VARCHAR(30) DEFAULT('') NOT NULL,
	USU_USUARIO VARCHAR(20) DEFAULT('') NOT NULL,
	USU_CONTRASEÑA VARCHAR(20) DEFAULT('') NOT NULL,
	USU_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	USU_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	USU_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	USU_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	USU_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_USUARIOS PRIMARY KEY NONCLUSTERED (PK_USUARIO, PK_RESTAURANTE)) 

 ALTER TABLE SIAD_USUARIOS ADD CONSTRAINT FK_SIAD_RES_USU FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE) 
 
 ALTER TABLE SIAD_USUARIOS ADD CONSTRAINT FK_SIAD_ROL_USU FOREIGN KEY(PK_ROL, PK_RESTAURANTE) REFERENCES SIAD_ROLES(PK_ROL, PK_RESTAURANTE) 

----------------------------------------------------------------------------------------------------
 
 CREATE TABLE SIAD_PAGINAS(
	PK_PAGINA SMALLINT IDENTITY(1,1) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	PAG_NOMBRE VARCHAR(30) DEFAULT('') NOT NULL,
	PAG_RUTA VARCHAR(100) DEFAULT('') NOT NULL,
	PAG_ICONO VARCHAR(30) DEFAULT('') NOT NULL,
	PAG_TIPO VARCHAR(50) DEFAULT('') NOT NULL,
	PAG_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	PAG_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	PAG_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	PAG_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	PAG_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_PAGINAS PRIMARY KEY NONCLUSTERED (PK_PAGINA, PK_RESTAURANTE))
 
 ALTER TABLE SIAD_PAGINAS ADD CONSTRAINT FK_SIAD_RES_PAG FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE) 
 

----------------------------------------------------------------------------------------------------
 
 CREATE TABLE SIAD_PAGINAS_POR_ROL(
	PK_PAGINA_POR_ROL SMALLINT IDENTITY(1,1) NOT NULL,
	PK_ROL SMALLINT DEFAULT(0) NOT NULL,
	PK_PAGINA SMALLINT DEFAULT(0) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	PPR_INGRESO VARCHAR(1) DEFAULT('') NOT NULL,
	PPR_CREACION VARCHAR(1) DEFAULT('') NOT NULL,
	PPR_MODIFICACION VARCHAR(1) DEFAULT('') NOT NULL,
	PPR_ELIMINACION VARCHAR(1) DEFAULT('') NOT NULL,
 CONSTRAINT PK_SIAD_PAGINAS_POR_ROL PRIMARY KEY NONCLUSTERED (PK_PAGINA_POR_ROL, PK_ROL, PK_PAGINA))
 
 ALTER TABLE SIAD_PAGINAS_POR_ROL ADD CONSTRAINT FK_SIAD_ROL_PPR FOREIGN KEY(PK_ROL, PK_RESTAURANTE) REFERENCES SIAD_ROLES(PK_ROL, PK_RESTAURANTE)
 
 ALTER TABLE SIAD_PAGINAS_POR_ROL ADD CONSTRAINT FK_SIAD_PAG_PPR FOREIGN KEY(PK_PAGINA, PK_RESTAURANTE) REFERENCES SIAD_PAGINAS(PK_PAGINA, PK_RESTAURANTE)
 
----------------------------------------------------------------------------------------------------
 
  CREATE TABLE SIAD_TIPO_MENU(
	PK_TIPO_MENU SMALLINT IDENTITY(1,1) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	TIM_NOMBRE VARCHAR(30) DEFAULT('') NOT NULL,
	TIM_DESCRIPCION VARCHAR(50) DEFAULT('') NOT NULL,
	TIM_CODIGO VARCHAR(20) DEFAULT('') NOT NULL,
	TIM_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	TIM_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	TIM_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	TIM_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	TIM_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_TIPO_MENU PRIMARY KEY NONCLUSTERED (PK_TIPO_MENU)) 

 ALTER TABLE SIAD_TIPO_MENU ADD CONSTRAINT FK_SIAD_RES_TIM FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE)
 
----------------------------------------------------------------------------------------------------

CREATE TABLE SIAD_PORCIONES(
	PK_PORCION SMALLINT IDENTITY(1,1) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	POR_NOMBRE VARCHAR(30) DEFAULT('') NOT NULL,
	POR_DESCRIPCION VARCHAR(50) DEFAULT('') NOT NULL,
	POR_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	POR_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	POR_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	POR_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	POR_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_PORCIONES PRIMARY KEY NONCLUSTERED (PK_PORCION, PK_RESTAURANTE)) 
 
 ALTER TABLE SIAD_PORCIONES ADD CONSTRAINT FK_SIAD_RES_POR FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE)

----------------------------------------------------------------------------------------------------
 CREATE TABLE SIAD_MENUS(
	PK_MENU SMALLINT IDENTITY(1,1) NOT NULL,
	PK_PORCION SMALLINT DEFAULT(0) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	PK_TIPO_MENU SMALLINT DEFAULT(0) NOT NULL,
	MEN_CODIGO VARCHAR(30) DEFAULT('') NOT NULL,
	MEN_NOMBRE VARCHAR(50) DEFAULT('') NOT NULL,
	MEN_IMAGEN IMAGE NULL,
	MEN_PRECIO DECIMAL(8,2) DEFAULT(0) NOT NULL,
	MEN_PRECIO_IVI DECIMAL(8,2) DEFAULT(0) NOT NULL,
	MEN_DESCUENTO DECIMAL(4,2) DEFAULT(0) NOT NULL,
	MEN_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	MEN_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	MEN_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	MEN_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	MEN_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_MENUS PRIMARY KEY NONCLUSTERED (PK_MENU, MEN_CODIGO)) 

 ALTER TABLE SIAD_MENUS ADD CONSTRAINT FK_SIAD_RES_MEN FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE) 

 ALTER TABLE SIAD_MENUS ADD CONSTRAINT FK_SIAD_TIM_MEN FOREIGN KEY(PK_TIPO_MENU) REFERENCES SIAD_TIPO_MENU(PK_TIPO_MENU) 
 
 ALTER TABLE SIAD_MENUS ADD CONSTRAINT FK_SIAD_POR_MEN FOREIGN KEY(PK_PORCION, PK_RESTAURANTE) REFERENCES SIAD_PORCIONES(PK_PORCION, PK_RESTAURANTE) 



 ----------------------------------------------------------------------------------------------------
 
 CREATE TABLE SIAD_PARAMETROS_GENERALES(
	PK_PARAMETRO_GENERAL SMALLINT IDENTITY(1,1) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	PGE_NOMBRE VARCHAR(50) DEFAULT('') NOT NULL,
	PGE_DESCRIPCION VARCHAR(50) DEFAULT('') NOT NULL,
	PGE_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	PGE_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	PGE_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	PGE_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	PGE_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_PARAMETROS_GENERALES PRIMARY KEY NONCLUSTERED (PK_PARAMETRO_GENERAL))
 
 ALTER TABLE SIAD_PARAMETROS_GENERALES ADD CONSTRAINT FK_SIAD_RES_PGE FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE) 
 

  ----------------------------------------------------------------------------------------------------
 
 CREATE TABLE SIAD_MESAS(
	PK_MESA SMALLINT IDENTITY(1,1) NOT NULL,
	PK_RESTAURANTE SMALLINT DEFAULT(0) NOT NULL,
	MES_NUMERO SMALLINT DEFAULT(0) NOT NULL,
	MES_DESCRIPCION VARCHAR(50) DEFAULT('') NOT NULL,
	MES_ESTADO_ACTUAL VARCHAR(50) DEFAULT('DISPONIBLE') NOT NULL,
	MES_ESTADO VARCHAR(1) DEFAULT('A') NOT NULL,
	MES_CREADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	MES_FECHA_CREACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
	MES_MODIFICADO_POR VARCHAR(20) DEFAULT('') NOT NULL,
	MES_FECHA_MODIFICACION SMALLDATETIME DEFAULT(GETDATE()) NOT NULL,
 CONSTRAINT PK_SIAD_MESAS PRIMARY KEY NONCLUSTERED (PK_MESA))
 
 ALTER TABLE SIAD_MESAS ADD CONSTRAINT FK_SIAD_RES_MES FOREIGN KEY(PK_RESTAURANTE) REFERENCES SIAD_RESTAURANTE(PK_RESTAURANTE) 
 

  ----------------------------------------------------------------------------------------------------

